name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: set release date
        shell: bash
        run: |
          echo "RELEASE_DATE=$(date '+%Y-%m-%d-%H-%M-%S')" >> ${GITHUB_ENV}
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        
      - name: download qt mysql driver
        shell: bash
        run: |
          mkdir qsqlmysql_5.15.2_MSVC2019_64
          curl https://github.com/thecodemonkey86/qt_mysql_driver/files/5575770/qsqlmysql.dll_Qt_SQL_driver_5.15.2_MSVC2019_64-bit.zip -o qsqlmysql5.15.2_MSVC2019_64.zip 
          unzip qsqlmysql5.15.2_MSVC2019_64.zip -d ./qsqlmysql_5.15.2_MSVC2019_64
          ls -alR ./qsqlmysql_5.15.2_MSVC2019_64

      - name: pack qt
        run: |
          7z a qt-dev-x86_64.zip "${{ env.Qt5_Dir }}"

      - uses: actions/upload-artifact@v4
        with:
          name: qt5-Qt
          path: |
            qt-dev-x86_64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: qt5-x86_64-vs2019
          tag_name: ${{ env.RELEASE_DATE }}
          files: qt-dev-x86_64.zip
