name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          dir: '${{ github.workspace }}/qt5'
          cache: true

      - name: Show the artifacts
        shell: bash
        run: |
          pwd
          tree "${{ github.workspace }}/qt5/QT" > output_tree.txt
          
      - uses: actions/upload-artifact@v4
        with:
          name: output_tree
          path: |
            output_tree.txt
