name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Show the artifacts
        shell: bash
        run: |
          pwd
          ls -alR "${{ env.Qt5_Dir }}"

      - uses: actions/upload-artifact@v4
        with:
          name: qt5-Qt
          path: |
            "${{ env.Qt5_Dir }}"
