name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: pack qt
        run: |
          7z a qt-dev-x86_64.zip "${{ env.Qt5_Dir }}"

      - uses: actions/upload-artifact@v4
        with:
          name: qt5-Qt
          path: |
            qt-dev-x86_64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: qt5-x86_64-vs2019
          tag_name: ${{ env.RELEASE_DATE }}
          files: qt-dev-x86_64.zip
